version: "3"

services:
  web-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  back-service:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5050:8080"