version: "3"

services:
  webappia:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backia:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"